In [1]:
! pip install numpy



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
scores = np.array([[85,90,78],[92,98,95],[76,95,85],[90,85,92],[88,76,89]])
scores

array([[85, 90, 78],
       [92, 98, 95],
       [76, 95, 85],
       [90, 85, 92],
       [88, 76, 89]])

In [5]:
mean_score=np.mean(scores , axis=0)
mean_score

array([86.2, 88.8, 87.8])

In [6]:
median_score=np.mean(scores , axis =0)
median_score

array([86.2, 88.8, 87.8])

In [25]:
sum_students=np.sum(scores,axis=1)
sum_students
max_no=np.max(sum_students)
max_no
index=np.argmax(sum_students) #for finding index of the sum of highest elements
index
print(scores[index])

[92 98 95]


In [9]:
min_marks=np.min(scores , axis =0)
min_marks

array([76, 76, 78])

In [10]:
max_marks=np.max(scores , axis =0)
max_marks

array([92, 98, 95])

In [12]:
newarr=scores.reshape(3,5)
newarr

array([[85, 90, 78, 92, 98],
       [95, 76, 95, 85, 90],
       [85, 92, 88, 76, 89]])

In [13]:
ascending_order=np.sort(scores , axis = 0)
ascending_order

array([[76, 76, 78],
       [85, 85, 85],
       [88, 90, 89],
       [90, 95, 92],
       [92, 98, 95]])

In [15]:
descending_order=np.sort(scores , axis = 0 )[::-1]
descending_order

array([[92, 98, 95],
       [90, 95, 92],
       [88, 90, 89],
       [85, 85, 85],
       [76, 76, 78]])

# EXCEPTION HANDLING

**compile time**
**run time**

In [26]:
L=[1,2,3,4]
L[3]

4

In [30]:
print("Hello World")
L
print(L[3])
try:
    print(L[2])
except:
    print("invalid code")
finally:
    
print("End of Code")

Hello World
4
3
End of Code


In [32]:
a=10
b=0
try:
    print(a/b)
except:
    print("B can't be zero")
finally:  #finally work all conditions whether we are giving error or not in try and except block
    print("Yesssss!!!")

B can't be zero
Yesssss!!!
